package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Integer codee;
     private String libellee;
     private String objectife;
     private String lienvideo;
     private String desc;
     private Integer dureeAttentue;
     private Integer nbAttentu;
     private Integer serie;
     private Integer tempsReposE;

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getDureeAttentue() {
        return dureeAttentue;
    }

    public void setDureeAttentue(Integer dureeAttentue) {
        this.dureeAttentue = dureeAttentue;
    }

    public Integer getNbAttentu() {
        return nbAttentu;
    }

    public void setNbAttentu(Integer nbAttentu) {
        this.nbAttentu = nbAttentu;
    }

    public Integer getSerie() {
        return serie;
    }

    public void setSerie(Integer serie) {
        this.serie = serie;
    }

    public Integer getTempsReposE() {
        return tempsReposE;
    }

    public void setTempsReposE(Integer tempsReposE) {
        this.tempsReposE = tempsReposE;
    }
    public Exercice() {
    }

    public Exercice(String libellee, String objectife, String lienvideo) {
       this.libellee = libellee;
       this.objectife = objectife;
       this.lienvideo = lienvideo;
    }
    public Exercice(Integer id,String libellee, String objectife, String lienvideo) {
       this.codee=id;
       this.libellee = libellee;
       this.objectife = objectife;
       this.lienvideo = lienvideo;
    }

    public Exercice(Integer codee, String libellee, String objectife, String lienvideo, String desc, Integer dureeAttentue, Integer nbAttentu, Integer serie, Integer tempsReposE) {
        this.codee = codee;
        this.libellee = libellee;
        this.objectife = objectife;
        this.lienvideo = lienvideo;
        this.desc = desc;
        this.dureeAttentue = dureeAttentue;
        this.nbAttentu = nbAttentu;
        this.serie = serie;
        this.tempsReposE = tempsReposE;
    }
   
    public Integer getCodee() {
        return this.codee;
    }
    
    public void setCodee(Integer codee) {
        this.codee = codee;
    }
    public String getLibellee() {
        return this.libellee;
    }
    
    public void setLibellee(String libellee) {
        this.libellee = libellee;
    }
    public String getObjectife() {
        return this.objectife;
    }
    
    public void setObjectife(String objectife) {
        this.objectife = objectife;
    }
    public String getLienvideo() {
        return this.lienvideo;
    }
    
    public void setLienvideo(String lienvideo) {
        this.lienvideo = lienvideo;
    }



}


