package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Planifierbilan generated by hbm2java
 */
public class Planifierbilan  implements java.io.Serializable {


     private PlanifierbilanId id;
     private Integer ordreb;
     private String nbmaxu;
     private Integer tempsmaxu;

    public Planifierbilan() {
    }

	
    public Planifierbilan(PlanifierbilanId id) {
        this.id = id;
    }
    public Planifierbilan(PlanifierbilanId id, Integer ordreb, String nbmaxu, Integer tempsmaxu) {
       this.id = id;
       this.ordreb = ordreb;
       this.nbmaxu = nbmaxu;
       this.tempsmaxu = tempsmaxu;
    }
   
    public PlanifierbilanId getId() {
        return this.id;
    }
    
    public void setId(PlanifierbilanId id) {
        this.id = id;
    }
    public Integer getOrdreb() {
        return this.ordreb;
    }
    
    public void setOrdreb(Integer ordreb) {
        this.ordreb = ordreb;
    }
    public String getNbmaxu() {
        return this.nbmaxu;
    }
    
    public void setNbmaxu(String nbmaxu) {
        this.nbmaxu = nbmaxu;
    }
    public Integer getTempsmaxu() {
        return this.tempsmaxu;
    }
    
    public void setTempsmaxu(Integer tempsmaxu) {
        this.tempsmaxu = tempsmaxu;
    }




}


