package model;
// Generated 28 mars 2018 10:29:50 by Hibernate Tools 4.3.1



/**
 * Seancetype generated by hbm2java
 */
public class Seancetype  implements java.io.Serializable {


     private Integer codest;
     private int codecat;
     private String libellest;
     private String descriptionst;

    public Seancetype() {
    }

	
    public Seancetype(int codecat) {
        this.codecat = codecat;
    }
    public Seancetype(int codecat, String libellest, String descriptionst) {
       this.codecat = codecat;
       this.libellest = libellest;
       this.descriptionst = descriptionst;
    }
   
    public Integer getCodest() {
        return this.codest;
    }
    
    public void setCodest(Integer codest) {
        this.codest = codest;
    }
    public int getCodecat() {
        return this.codecat;
    }
    
    public void setCodecat(int codecat) {
        this.codecat = codecat;
    }
    public String getLibellest() {
        return this.libellest;
    }
    
    public void setLibellest(String libellest) {
        this.libellest = libellest;
    }
    public String getDescriptionst() {
        return this.descriptionst;
    }
    
    public void setDescriptionst(String descriptionst) {
        this.descriptionst = descriptionst;
    }




}


